url : https://www.youtube.com/watch?v=VKhFeh92eps&t=4s

Pytorch란?
파이썬 기반 패키지로, Numpy의 연산을 GPU로 가속화할 수 있게 함.

**[목차]**
1. Torch의 Tensor
2. Tensor의 선언
3. Numpy to Tensor
4. Tensor to Numpy
5. Tensor의 view
6. Tensor의 cat
7. Tensor의 mean, sum
8. Tensor의 GPU 연산

#### 1. Torch의 Tensor
- Tensor는 pytorch의 자료 형으로 단일 데이터 타입으로 된 자료들의 다차원 행렬임.
- Tensor는 간단한 명령어를 통해서 GPU로 연산을 수행하게 만들 수 있음.
- Tensor 변수 뒤에 .cuda()를 추가하면 됨.
- Tensor의 종류는 float, Double 등이 있고 CPU Tensor와 GPU Tensor가 있음.

#### 2. Tensor의 선언

In [2]:
import torch

torch.Tensor(크기) 로 선언하며, default로 floatTensor가 만들어짐.

In [3]:
# torch.Tensor(크기), 1차원 크기가 3
x=torch.Tensor(3)
x

tensor([-9.7401e+05,  4.5902e-41, -9.7401e+05])

In [4]:
# 3x3 인 2차원 행렬
x2 = torch.Tensor(3,3)
x2

tensor([[       0.0000,        0.0000, -3816732.0000],
        [       0.0000,       -0.0352,        0.0000],
        [-3890840.0000,        0.0000,        0.0000]])

#### 3. Tensor의 random 선언

In [5]:
# rand : 0에서 1 사이의 uniform distribution random 값으로 선언
a = torch.rand(3,3)
a

tensor([[0.5238, 0.0442, 0.8026],
        [0.8273, 0.8513, 0.4949],
        [0.7589, 0.1611, 0.9587]])

In [6]:
# randn : 평균이 0이고, 분산이 1인 normal distribution random 값으로 선언
b = torch.randn(3,3)
b

tensor([[ 0.0492, -1.8733,  1.8210],
        [ 1.6929, -0.8383, -0.6945],
        [-0.9241, -1.0083,  1.9984]])

#### 4. Numpy에서 Tensor로

numpy 에서 생성된 array를 tensor로 변환

torch.Tensor(numpy array)

In [7]:
import numpy as np

In [9]:
c = np.array([1,2,3,4])
d = torch.Tensor(c)
d

tensor([1., 2., 3., 4.])

#### 5. Tensor에서 Numpy

tensor를 numpy로 변환

Tensor_A.numpy()

In [10]:
e = torch.rand(3,3)
f = e.numpy()
f

array([[0.9952328 , 0.47932202, 0.18663388],
       [0.04709536, 0.29603964, 0.60475117],
       [0.5830979 , 0.4129746 , 0.82260716]], dtype=float32)

#### 6. Tensor의 형태 변환 (view)

행렬의 형태 변환. view를 사용.

In [13]:
# 3x3 2차원 행렬
g = torch.rand(3,3)
g

tensor([[0.7279, 0.3098, 0.3187],
        [0.9952, 0.9025, 0.9282],
        [0.9870, 0.4076, 0.4622]])

In [15]:
# 1x1x3x3 4차원 행렬
g = g.view(1,1,3,3)
g

tensor([[[[0.7279, 0.3098, 0.3187],
          [0.9952, 0.9025, 0.9282],
          [0.9870, 0.4076, 0.4622]]]])

#### 7. Tensor 합치기

torch.cat((Tensor_A, Tensor_B), dim) 여러개의 tensor를 특정 차원에 맞게 합칠 수 있는 함수.
두개의 텐서를 이어 붙임. dim 은 붙이고자 하는 차원

In [16]:
t1= torch.randn(1,1,3,3)
t2 = torch.randn(1,1,3,3)

In [17]:
t1

tensor([[[[-0.1796, -1.0482, -1.1168],
          [ 0.6346,  0.4550, -1.3169],
          [-0.4109,  1.9052, -0.0394]]]])

In [18]:
t2

tensor([[[[-0.1213, -0.6125, -0.6018],
          [ 1.4280, -1.1580,  0.6506],
          [-0.1472, -1.4417,  1.6785]]]])

In [22]:
t30 = torch.cat((t1,t2),0)
t30

tensor([[[[-0.1796, -1.0482, -1.1168],
          [ 0.6346,  0.4550, -1.3169],
          [-0.4109,  1.9052, -0.0394]]],


        [[[-0.1213, -0.6125, -0.6018],
          [ 1.4280, -1.1580,  0.6506],
          [-0.1472, -1.4417,  1.6785]]]])

In [23]:
t31 = torch.cat((t1,t2),1)
t31

tensor([[[[-0.1796, -1.0482, -1.1168],
          [ 0.6346,  0.4550, -1.3169],
          [-0.4109,  1.9052, -0.0394]],

         [[-0.1213, -0.6125, -0.6018],
          [ 1.4280, -1.1580,  0.6506],
          [-0.1472, -1.4417,  1.6785]]]])

In [24]:
t32 = torch.cat((t1,t2),dim=2)
t32

tensor([[[[-0.1796, -1.0482, -1.1168],
          [ 0.6346,  0.4550, -1.3169],
          [-0.4109,  1.9052, -0.0394],
          [-0.1213, -0.6125, -0.6018],
          [ 1.4280, -1.1580,  0.6506],
          [-0.1472, -1.4417,  1.6785]]]])

In [25]:
t33 = torch.cat((t1,t2),3)
t33

tensor([[[[-0.1796, -1.0482, -1.1168, -0.1213, -0.6125, -0.6018],
          [ 0.6346,  0.4550, -1.3169,  1.4280, -1.1580,  0.6506],
          [-0.4109,  1.9052, -0.0394, -0.1472, -1.4417,  1.6785]]]])

#### 8. Tensor 계산을 GPU

In [28]:
x = torch.rand(3,3)
y = torch.rand(3,3)

In [31]:
x

tensor([[0.3349, 0.4465, 0.8034],
        [0.8794, 0.9654, 0.5880],
        [0.7554, 0.5232, 0.0335]], device='cuda:0')

In [32]:
y

tensor([[0.6500, 0.2014, 0.3785],
        [0.3951, 0.1869, 0.6048],
        [0.0492, 0.6985, 0.1968]], device='cuda:0')

In [29]:
if torch.cuda.is_available():
    x=x.cuda()
    y=y.cuda()
    sum = x+y

In [30]:
sum

tensor([[0.9849, 0.6480, 1.1819],
        [1.2745, 1.1523, 1.1927],
        [0.8046, 1.2218, 0.2304]], device='cuda:0')

Tensor_A.mean() #Tensor_A의 평균.

Tensor_A.sum() #Tensor_A의 원소합.

등 많은 함수 이미 구현되어 있음.