#### torch.nn && toch.nn.functional

nn과 nn.functional이 제공하는 기능은 유사. 사용하는 방법에 차이가 있음. **Conv2d**를 사용하여 어떤 차이가 있는지 확인할 것임.

#### 1. torch.nn.Conv2d(in_channels, out_channels, kernel_size)

out_channel : 사용하고자 하는 필터의 개수

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

In [3]:
input = torch.ones(1,1,3,3)
filter = torch.ones(1,1,3,3) # torch.nn.functional에서는 filter(weight)를 직접 설정해야 함.

input = Variable(input, requires_grad = True) # input, filter는 Variable로 설정해야 함.
print(input)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)


In [5]:
filter = Variable(filter)

In [6]:
out = F.conv2d(input, filter)
print(out)

tensor([[[[9.]]]], grad_fn=<ThnnConv2DBackward>)


In [7]:
out.backward()
print(out.grad_fn)

In [8]:
print(input.grad)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


In [9]:
input2 = Variable(torch.ones(1,1,3,3), requires_grad = True)
filter2 = filter+1
out2 = F.conv2d(input2, filter2)

In [10]:
print(out2)

tensor([[[[18.]]]], grad_fn=<ThnnConv2DBackward>)


In [11]:
out2.backward()
print(out2.grad_fn)

In [12]:
print(input2.grad)

tensor([[[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]]])


#### 2. nn.Conv2d
- 자동으로 bias value를 가지고 있음.

In [13]:
input3 = torch.ones(1,1,3,3)
input3 = Variable(input3, requires_grad=True)

In [14]:
# 사용할 함수를 func라는 공간에 넣음. (in_channel, out_channel, kernel_size)
# 1개의 이미지가 들어가서 1개의 이미지가 나오는데, 이때 filter의 크기는 3*3 이다.
func = nn.Conv2d(1,1,3) 

In [15]:
func.weight

Parameter containing:
tensor([[[[ 0.1900,  0.1411,  0.0712],
          [-0.0715, -0.0582,  0.0813],
          [-0.0865, -0.2767,  0.1186]]]], requires_grad=True)

In [16]:
out3 = func(input3)
print(out3)

tensor([[[[0.1096]]]], grad_fn=<ThnnConv2DBackward>)


In [17]:
out3.backward()
print(input3.grad)

tensor([[[[ 0.1900,  0.1411,  0.0712],
          [-0.0715, -0.0582,  0.0813],
          [-0.0865, -0.2767,  0.1186]]]])


#### 3. 큰 사이즈의 conv2d
- 5*5 input
- 3*3 filter

In [18]:
input4 = torch.ones(1,1,5,5)
input4 = Variable(input4, requires_grad = True)
input4

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]], requires_grad=True)

In [19]:
filter4 = nn.Conv2d(1,1,3, bias = None)

In [20]:
filter4

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), bias=False)

In [21]:
print(filter4.weight)

Parameter containing:
tensor([[[[ 0.0899, -0.3318, -0.2266],
          [ 0.2671, -0.1130,  0.0626],
          [-0.2360, -0.0116,  0.2784]]]], requires_grad=True)


In [24]:
filter4.weight = torch.nn.Parameter(torch.ones(1,1,3,3)+1)
filter4.weight

Parameter containing:
tensor([[[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]]], requires_grad=True)

In [25]:
out4 = filter4(input4)

In [26]:
print(out4)

tensor([[[[18., 18., 18.],
          [18., 18., 18.],
          [18., 18., 18.]]]], grad_fn=<ThnnConv2DBackward>)
